### PR TITLE
change document.exeCommand to clipboard API

### LINKED ISSUE #85: Replace document.execCommand("copy") with clipboard API
We're currently copying text to the clipboard like this:

https://github.com/mkasberg/script-seed/blob/f8fc60cfa72a9b666fbbcc80cc96c500a9bcb0c1/main.js#L111-L130

However, the [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) API is deprecated.

We should replace it with [Clipboard.writeText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText).

I'm not 100% sure, but this might be difficult to test locally if the clipboard API requires HTTPS...

Also, note that we might be able to remove some code that selects the text before executing `copy` since with the new API we can just get the inner text and write it directly to the clipboard.

### PR DESCRIPTION
**Pull request by AloyBranCheung**
Closes #85 

To maintain text highlighting when the button is clicked I kept the origin code.

To switch to clipboard API, I just replaced `document.execCommand("copy")` with `  navigator.clipboard.writeText(element.innerText);
`

### CODE REVIEW

**Review by mkasberg — CHANGES_REQUESTED** [review]
* As specified in #85, please remove the code that performs highlighting. There is no longer any reason to highlight code when the button is clicked.
* It appears that your editor reformatted the `main.js` file. Please remove the reformatting so that your commit only changes lines of code that need to be changed.

**Comment by AloyBranCheung** [comment]
Will do. In terms of the highlighting, would you like to replace that with something else for better user feedback/UX when clicking the copy button?

**Comment by AloyBranCheung** [comment]
Ok, I removed the formatting and highlighting.

**Review by mkasberg — APPROVED** [review]
Looks good, thanks for the contribution!

> In terms of the highlighting, would you like to replace that with something else for better user feedback/UX when clicking the copy button?

Perhaps if would make sense to show a small notice to the user like "Copied to clipboard" or something. If you want to pursue that, you're welcome to do so in a new PR and I'll take a look.

**Comment by mkasberg** [comment]
Similar to what GitHub does at the top of this page when you click the little icon next to the branch name.

**Pull request merged**
